

name: Python application

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest
      - name: discord-webhook
        # You may pin to the exact commit or the version.
        # uses: johnnyhuy/actions-discord-git-webhook@ba54912b26910da886c9095317d6da6182a87224
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          # Discord webhook URL
          webhook_url: "https://discord.com/api/webhooks/1083479100427092029/Xk2nRMnd1XToOXgBMqwIehuARsHJCYd-mPIvygRs8AwidRol4PtyTpKpC7sW-WVyOVhz"
      