

name: Python application

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest
      - name: Slack Webhook
        # You may pin to the exact commit or the version.
        # uses: zrosenbauer/slacktion@f3920a4f79a459226ecf1f91e627a21d63eb67b0
        uses: zrosenbauer/slacktion@1.1.5
        with:
          # Use to specify the username for the published message.
          username: # optional
          # Use to define the message that will be sent to slack.
          text: 
          # Use to define the webhook URL used to send a message.
          webhook_url: https://hooks.slack.com/services/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
          # Use to specify an emoji (using colon shortcodes, eg. :white_check_mark:) to use as the profile photo alongside the message.
          icon_emoji: # optional
          # Use to specify a URL to an image to use as the profile photo alongside the message.
          icon_url: # optional
            
      