

name: Python application

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest
      - name: Discord Webhook Messages
        # You may pin to the exact commit or the version.
        # uses: bythope/discord-webhook-messages@3b3af1ab7923c77fa96ca1d50624a91cfc9d983c
        uses: bythope/discord-webhook-messages@v1.1.0
        with:
          # A full discord webhook url
          webhookUrl: "https://discord.com/api/webhooks/1083489099538759741/dG6jBwR18uIQcAkMXR-lZO3VCv7giogWJ0tWO6Hb1IOfQhKvCqPSMKOCeFAtbm37pWZp"
          # Event handler
          handler: 