

name: Python application

on: push

jobs:
     build:

     runs-on: windows-latest
     timeout-minutes: 5

steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pylint -m pip install --upgrade pip
      - name: Run tests
        run: |
          pip install pytest
          python -m pytest